version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:8.3
    environment:
      MYSQL_DATABASE: 'mars'
      MYSQL_USER: 'mars'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - '127.0.0.1:3307:3306'
    expose:
      - '3306'
    volumes:
      - mars_db:/var/lib/mysql
  mars_dev:
    container_name: mars_dev
    image: mars_image:latest
    pull_policy: never
    build:
      context: ./docker-dev-setup
    depends_on:
      - mysql
    volumes:
      - ".:/workspace/mars"
    ports:
      - '127.0.0.1:8000:8000'

volumes:
  mars_db: